/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2016-06-07 04:19:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class startwelcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\"><head>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <title>Happy Ride | Created By Students of BVRIT</title>\n");
      out.write("  <meta name=\"keywords\" content=\"\">\n");
      out.write("  <meta name=\"description\" content=\"\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">\n");
      out.write("  \n");
      out.write("  <meta property=\"og:title\" content=\"\">\n");
      out.write("\t<meta property=\"og:type\" content=\"website\">\n");
      out.write("\t<meta property=\"og:url\" content=\"\">\n");
      out.write("\t<meta property=\"og:site_name\" content=\"\">\n");
      out.write("\t<meta property=\"og:description\" content=\"\">\n");
      out.write("\n");
      out.write("  <!-- Styles -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/animate.css\">\n");
      out.write("  <link href='http://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800,900|Montserrat:400,700' rel='stylesheet' type='text/css'>\n");
      out.write("  <script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/main.css\">\n");
      out.write("\n");
      out.write("  <script src=\"js/modernizr-2.7.1.js\"></script>\n");
      out.write("  <script>\n");
      out.write("\n");
      out.write("  \t$( document ).ready(function() {\n");
      out.write(" \t\tvar myNewVariable = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\n");
      out.write(" \t\t$(\"#msg\").html(myNewVariable);\n");
      out.write("  \t});\n");
      out.write("  \t</script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <div class=\"navbar navbar-inverse navbar-fixed-top\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"navbar-header\">\n");
      out.write("        \n");
      out.write("        \n");
      out.write("          <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\n");
      out.write("            <span class=\"icon-bar\"></span>\n");
      out.write("            <span class=\"icon-bar\"></span>\n");
      out.write("            <span class=\"icon-bar\"></span>\n");
      out.write("          </button>\n");
      out.write("          <a class=\"logo\" href=\"index.html\"><img src=\"img/logo.jpg\" width = \"50\" height = \"50\" alt=\"Logo\"></a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"navbar-collapse collapse\">\n");
      out.write("          <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("            <li><a href=\"licence.jsp\" class=\"scroll\">offer ride</a></li>\n");
      out.write("            <li><a href=\"#\">login</a></li>\n");
      out.write("            \n");
      out.write("          </ul>\n");
      out.write("        </div><!--/.navbar-collapse -->\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("        \n");
      out.write("    <header>\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-xs-6\">\n");
      out.write("            <a href=\"index.html\"><img src=\"img/logo.jpg\" width = \"50\" height = \"50\" alt=\"Logo\"></a>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-xs-6 signin text-right navbar-nav\">\n");
      out.write("            <a href=\"#pricing\" class=\"scroll\"></a>&nbsp; &nbsp;<a href= \"\"></a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"row header-info\">\n");
      out.write("          <div class=\"col-sm-10 col-sm-offset-1 text-center\">\n");
      out.write("          \t\t            <h1 id=\"msg\" style=\"color:red\"></h1>\n");
      out.write("            <h2 class=\"wow fadeIn\">A Happy ride theme</h2>\n");
      out.write("            <br />\n");
      out.write("            <p class=\"lead wow fadeIn\" data-wow-delay=\"0.5s\">car with different colours. <br>\n");
      out.write("            car with different models.</p>\n");
      out.write("            <br />\n");
      out.write("              \n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                  <div class=\"col-xs-6 text-right wow fadeInUp\" data-wow-delay=\"1s\">\n");
      out.write("                    <a href=\"#be-the-first\" class=\"btn btn-secondary btn-lg scroll\">Learn More</a>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"col-xs-6 text-left wow fadeInUp\" data-wow-delay=\"1.4s\">\n");
      out.write("                    <a href=\"#invite\" class=\"btn btn-primary btn-lg scroll\">Login</a>\n");
      out.write("                     \n");
      out.write("                  </div>\n");
      out.write("                </div><!--End Button Row-->  \n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("   \n");
      out.write("    </header>\n");
      out.write("    \n");
      out.write("    <div class=\"mouse-icon hidden-xs\">\n");
      out.write("\t\t\t\t<div class=\"scroll\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("    \n");
      out.write("    <section id=\"be-the-first\" class=\"pad-xl\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-sm-8 col-sm-offset-2 text-center margin-30 wow fadeIn\" data-wow-delay=\"0.6s\">\n");
      out.write("            <h2>Be the first</h2>\n");
      out.write("            <p class=\"lead\">Different models of cars.</p>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"iphone wow fadeInUp\" data-wow-delay=\"1s\">\n");
      out.write("\t        <img src=\"img/iphone.png\">\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </section>\n");
      out.write("      <!-- bottom-up button -->\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://arrow.scrolltotop.com/arrow7.js\"></script>\n");
      out.write("<noscript>Not seeing a <a href=\"http://www.scrolltotop.com/\">Scroll to Top Button</a>? Go to our FAQ page for more info.</noscript>\n");
      out.write("    <!-- end bottom up button -->\n");
      out.write("    <section id=\"main-info\" class=\"pad-xl\">\n");
      out.write("\t    <div class=\"container\">\n");
      out.write("\t\t    <div class=\"row\">\n");
      out.write("\t\t\t    <div class=\"col-sm-4 wow fadeIn\" data-wow-delay=\"0.4s\">\n");
      out.write("\t\t\t\t    <hr class=\"line purple\">\n");
      out.write("\t\t\t\t    <h3>App Feature One Here</h3>\n");
      out.write("\t\t\t\t    <p>You find lots of joy.</p>\n");
      out.write("\t\t\t    </div>\n");
      out.write("\t\t\t    <div class=\"col-sm-4 wow fadeIn\" data-wow-delay=\"0.8s\">\n");
      out.write("\t\t\t\t    <hr  class=\"line blue\">\n");
      out.write("\t\t\t\t    <h3>App Feature One Here</h3>\n");
      out.write("\t\t\t\t    <p>You can save money here.</p>\n");
      out.write("\t\t\t    </div>\n");
      out.write("\t\t\t    <div class=\"col-sm-4 wow fadeIn\" data-wow-delay=\"1.2s\">\n");
      out.write("\t\t\t\t    <hr  class=\"line yellow\">\n");
      out.write("\t\t\t\t    <h3>App Feature One Here</h3>\n");
      out.write("\t\t\t\t    <p>You can save time here.</p>\n");
      out.write("\t\t\t    </div>\n");
      out.write("\t\t    </div>\n");
      out.write("\t    </div>\n");
      out.write("    </section>\n");
      out.write("        \n");
      out.write("        \n");
      out.write("    <!--Pricing-->\n");
      out.write("    <section id=\"pricing\" class=\"pad-lg\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"row margin-40\">\n");
      out.write("          <div class=\"col-sm-8 col-sm-offset-2 text-center\">\n");
      out.write("            <h2 class=\"white\">pricing</h2>\n");
      out.write("            <p class=\"white\">white color is so beautiful.</p>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"row margin-50\">\n");
      out.write("          \n");
      out.write("          \n");
      out.write("      \n");
      out.write("          <div class=\"col-sm-4 pricing-container wow fadeInUp\" data-wow-delay=\"1.3s\">\n");
      out.write("            <br />\n");
      out.write("            <ul class=\"list-unstyled pricing-table text-center\">\n");
      out.write("    \t\t\t\t\t<li class=\"headline\"><h5 class=\"white\">Business</h5></li>\n");
      out.write("    \t\t\t\t\t<li class=\"price\"><div class=\"amount\">24000<small>/m</small></div></li>\n");
      out.write("    \t\t\t\t\t<li class=\"info\">2 row section for you package information. You can include all details or icons</li>\n");
      out.write("    \t\t\t\t\t<li class=\"features first\">Up To 25 cars</li>\n");
      out.write("    \t\t\t\t\t<li class=\"features\">10GB Storage</li>\n");
      out.write("    \t\t\t\t\t<li class=\"features\">Other info</li>\n");
      out.write("    \t\t\t\t\t<li class=\"features last btn btn-secondary btn-wide\"><a href=\"#\">Get Started</a></li>\n");
      out.write("    \t\t\t\t</ul>\n");
      out.write("          </div>\n");
      out.write("          \n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("      </div>\n");
      out.write("    </section>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <section id=\"invite\" class=\"pad-lg light-gray-bg\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-sm-8 col-sm-offset-2 text-center\">\n");
      out.write("            <i class=\"fa fa-envelope-o margin-40\"></i>\n");
      out.write("            <h2 class=\"black\">Get the invite</h2>\n");
      out.write("            <br />\n");
      out.write("            <br />\n");
      out.write("            \n");
      out.write("             <div class=\"row\">\n");
      out.write("              <div class=\"col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3\">\n");
      out.write("                <form role=\"form\" action = \"login\">\n");
      out.write("                  <div class=\"form-group\">\n");
      out.write("                   <input type=text class=\"form-control\" name=\"username\" placeholder=\"Enter username\">\n");
      out.write("                   <input type=password class=\"form-control\" name=\"password\" placeholder=\"Enter Password\">\n");
      out.write("                   \n");
      out.write("                  </div>\n");
      out.write("                  <button type=\"submit\" class=\"btn btn-primary btn-lg\">Login</button>\n");
      out.write("                  \n");
      out.write("               <a href = \"signup.jsp\">SignUp</a> \n");
      out.write("                  \n");
      out.write("                </form>\n");
      out.write("              </div>\n");
      out.write("            </div><!-- End Form row  -->\n");
      out.write("\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </section> \n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <section id=\"press\" class=\"pad-sm\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        \n");
      out.write("        <div class=\"row margin-30 news-container\">\n");
      out.write("          <div class=\"col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 wow fadeInLeft\" data-wow-delay=\"0.8s\">\n");
      out.write("            <a href=\"#\" target=\"_blank\">\n");
      out.write("            <img class=\"news-img pull-left\" src=\"img/press-01.jpg\" alt=\"Tech Crunch\">\n");
      out.write("            <p class=\"black\">You can find different types of models here.<br /> \n");
      out.write("            <small><em>Tech Crunch - January 15, 2015</em></small></p>\n");
      out.write("            </a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"row margin-30 news-container\">\n");
      out.write("          <div class=\"col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 wow fadeInLeft\" data-wow-delay=\"1.2s\">\n");
      out.write("            <a href=\"#\" target=\"_blank\">\n");
      out.write("            <img class=\"news-img pull-left\" src=\"img/press-02.jpg\" alt=\"Forbes\">\n");
      out.write("            <p class=\"black\">blue also looks beautiful. <br /> \n");
      out.write("            <small><em>Forbes - Feb 25, 2015</em></small></p>\n");
      out.write("            </a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("      </div>\n");
      out.write("    </section>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <footer>\n");
      out.write("      <div class=\"container\">\n");
      out.write("        \n");
      out.write("        <div class=\"row\">\n");
      out.write("         \n");
      out.write("          \n");
      out.write("          <div class=\"col-sm-4 text-right\">\n");
      out.write("            <p><small>Copyright &copy; 2016. All rights reserved. <br>\n");
      out.write("\t            Created by <a href=\"http://visualsoldiers.com\">Visual Soldiers</a></small></p>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("      </div>\n");
      out.write("    </footer>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <!-- Javascript\n");
      out.write("    ================================================== -->\n");
      out.write("    <!-- Placed at the end of the document so the pages load faster -->\n");
      out.write("    <script src=\"//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js\"></script>\n");
      out.write("    <script>window.jQuery || document.write('<script src=\"js/jquery-1.11.0.min.js\"><\\/script>')</script>\n");
      out.write("    <script src=\"js/wow.min.js\"></script>\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"js/main.js\"></script>\n");
      out.write("\n");
      out.write("     \n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
