/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2016-06-07 04:25:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE HTML>\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<title>Happy ride</title>\n");
      out.write("\t\t<link href=\"web/css/style.css\" rel=\"stylesheet\" type=\"text/css\"  media=\"all\" />\n");
      out.write("\t\t<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>\n");
      out.write("\t\t<link href=\"web/css/slider.css\" rel=\"stylesheet\" type=\"text/css\"  media=\"all\" />\n");
      out.write("\t\t  <script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js\"></script>\n");
      out.write("\t\t  <script type=\"text/javascript\" src=\"web/js/jquery.easing.1.3.js\"></script> \n");
      out.write("\t\t    <script type=\"text/javascript\" src=\"web/js/camera.min.js\"></script>\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t   jQuery(function(){\n");
      out.write("\t\t\t\tjQuery('#camera_wrap_1').camera({\n");
      out.write("\t\t\t\t\theight: '500px',\n");
      out.write("\t\t\t\t\tpagination: false,\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t});\n");
      out.write("\t\t  </script>\n");
      out.write("\t\t  <script type=\"text/javascript\">\n");
      out.write("\t\t\tjQuery(document).ready(function($) {\n");
      out.write("\t\t\t\t$(\".scroll\").click(function(event){\t\t\n");
      out.write("\t\t\t\t\tevent.preventDefault();\n");
      out.write("\t\t\t\t\t$('html,body').animate({scrollTop:$(this.hash).offset().top},200);\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t});\n");
      out.write("\t\t</script>\n");
      out.write("\t</head>\n");
      out.write("\t<body>\n");
      out.write("\t");
 
		String username =(String) session.getAttribute("username");
	
      out.write("\n");
      out.write("\t<!----start-wrap----->\n");
      out.write("\t<div class=\"wrap\">\n");
      out.write("\t\t<!----start-header----->\n");
      out.write("\t\t<div class=\"header\"  id=\"top\">\n");
      out.write("\t\t\t<!----top-header----->\n");
      out.write("\t\t\t<div class=\"top-header\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"clear\"> </div>\n");
      out.write("\t\t\t</div> \n");
      out.write("\t\t\t<!----End-top-header----->\n");
      out.write("\t\t\t<!---start-top-nav---->\n");
      out.write("\t\t\t<div class=\"top-nav\">\n");
      out.write("\t\t\t\t<div class=\"top-nav-left\">\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"welcome.jsp\"><img src=\"images/logo.jpg\" width = 90px; title=\"logo\" /></a></li>\n");
      out.write("\t\t\t\t\t\t<li ><a href=\"licence.jsp\">offer ride</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"findride\">take ride</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"profileview.jsp\">profile view</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"startwelcome.jsp\">logout</a>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<div class=\"clear\"> </div>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"top-nav-right\">\n");
      out.write("\t\t\t\t\t<form>\n");
      out.write("\t\t\t\t\t\t<input type=\"text\"><input type=\"submit\" value=\"\" /></form>\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"clear\" style=\"font-style: initial;font-size: 20px;\">Welcome ");
      out.print(username);
      out.write("!</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!---End-top-nav---->\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!----End-header----->\n");
      out.write("\t</div>\n");
      out.write("\t<!----End-wrap----->\n");
      out.write("\t<!--start-image-slider---->\n");
      out.write("\t\t\t<div class=\"slider\">\t\t\t\t\t     \n");
      out.write("\t\t\t\t\t<div class=\"camera_wrap camera_azure_skin\" id=\"camera_wrap_1\">\t\t\t\t\t\t\t\t\t           \n");
      out.write("\t\t\t\t\t\t<div data-src=\"images/car1.jpg\">  </div> \n");
      out.write("\t\t\t\t\t\t<div data-src=\"images/carpool.jpg\">  </div>\n");
      out.write("\t\t\t\t\t\t<div data-src=\"images/share.jpg\">  </div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"clear\"> </div>\t\t\t\t\t       \n");
      out.write("\t\t\t</div>\t\t\t\t\t\n");
      out.write("\t\t <!--End-image-slider---->\n");
      out.write("\t\t <!---start-content---->\n");
      out.write("\t\t <div class=\"content\">\n");
      out.write("\t\t \t<div class=\"top-grids\">\n");
      out.write("\t\t \t\t<div class=\"wrap\">\n");
      out.write("\t\t\t \t\t<div class=\"top-grid\">\n");
      out.write("\t\t\t \t\t\t<a href=\"salepost1.jsp\"><img src=\"images/2.png\" title=\"icon-name\"></a>\n");
      out.write("\t\t\t \t\t\t<h3>join</h3>\n");
      out.write("\t\t\t \t\t\t<p>it's quick ,simple and free </p>\n");
      out.write("\t\t\t \t\t\t<!--  <a class=\"button\" href=\"#\">Submit</a>-->\n");
      out.write("\t\t\t \t\t</div>\n");
      out.write("\t\t\t \t\t<div class=\"top-grid\">\n");
      out.write("\t\t\t \t\t\t<a href=\"PostFile.jsp\"><img src=\"images/6.png\" title=\"icon-name\"></a>\n");
      out.write("\t\t\t \t\t\t<h3>offer/book a ride</h3>\n");
      out.write("\t\t\t \t\t\t<p>search rides on your way and book seats  </p>\n");
      out.write("\t\t\t \t    <!--<a class=\"button\" href=\"#\">Submit</a>-->\n");
      out.write("\t\t\t \t\t\t\n");
      out.write("\t\t\t \t\t</div>\n");
      out.write("\t\t\t \t\t<div class=\"top-grid last-topgrid\">\n");
      out.write("\t\t\t \t\t\t<a href=\"RentLog1.jsp\"><img src=\"images/4.png\" title=\"icon-name\"></a>\n");
      out.write("\t\t\t \t\t\t<h3>travel together</h3>\n");
      out.write("\t\t\t \t\t\t<p>save time and money </p>\n");
      out.write("\t\t\t \t\t<!--<a class=\"button\" href=\"#\">Submit</a>-->\n");
      out.write("\t\t\t \t\t</div>\n");
      out.write("\t\t\t \t\t<div class=\"clear\"> </div>\n");
      out.write("\t\t \t\t</div>\n");
      out.write("\t\t \t</div>\n");
      out.write("\t</div>\n");
      out.write("\t</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
